// Generated by CIRCT firtool-1.62.0
module Adder(
  input        clock,
               reset,
  input  [7:0] io_a,
               io_b,
  output [7:0] io_c
);

  assign io_c = io_a + io_b;
endmodule

